---
- hosts: all
  roles:
    - { role: ca, become: True }
    - { role: adduser, become: yes }
    - { role: kubeconfig, become: yes }
    - { role: geerlingguy.ntp, ntp_timezone: Asia/Taipei, become: True }
